### ISSUE TITLE
Adverse effects if the system were to fail - Task 7

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#11]

**Comment by JunKai-Li-1** [comment]
Technological progress has brought countless benefits to the business, but an IT failure is a disaster for the enterprises. The failure of the information system could bring a massive impact to the business, employee and the customer. The first impact is the loss of customers and market share, as the information failures happened relationship managers would no longer get the support from it. It will lead the customer called an unprepared and unprofessional relationship managers and result in an unsatisfactory reply, which it will caused huge market and financial loss to the business. Continued with it, as the information system failure occur, business will need to spend a lots of time and manpower to solve it until it resumes operation. Every minute of the system downtime, would cause a significant drop of the work efficiency and increase financial costs. After the information system goes back online, the high investment on solving the IT failures might cause the business to fire a large range of employee to maintain the business as normal. The missing or corrupted data might also occur after the IT failures, the loss or damage of RM and customers' detail will takes a long time to resolve.
