### ISSUE TITLE
Use case diagram for customer call in

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#12]

**Comment by AungKMyat** [comment]
![Screen Shot 2020-05-16 at 10 25 09 pm](https://user-images.githubusercontent.com/52432394/82119711-1c282a80-97c4-11ea-80b6-ffb4242b73bb.png)

**Comment by JunKai-Li-1** [comment]
![Usu Case Call in](https://user-images.githubusercontent.com/62220299/82148539-fe2bfa00-9897-11ea-8753-cc2fccdfdfec.PNG)

**Comment by JunKai-Li-1** [comment]
![Usu Case Call in](https://user-images.githubusercontent.com/62220299/82630289-a09c0280-9c35-11ea-8826-4df3c0b7cd76.PNG)

**Comment by AungKMyat** [comment]
![Screen Shot 2020-05-27 at 12 35 20 am](https://user-images.githubusercontent.com/52432394/82913738-07147e00-9fb2-11ea-9842-ce476dc61b6d.png)

**Comment by JunKai-Li-1** [comment]
![Usu Case Call in](https://user-images.githubusercontent.com/62220299/82973433-b6853b00-a01a-11ea-969c-c0b07855e53e.PNG)
