### ISSUE TITLE
Activity diagram for call in

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#14]

**Comment by JunKai-Li-1** [comment]
![Activity Diagram Call In - Visio Professional 2020_5_16 16_36_41](https://user-images.githubusercontent.com/62220299/82118914-930df500-97bd-11ea-8b77-c6c3fe139a77.png)

**Comment by JunKai-Li-1** [comment]
Description:
Inbound calls begin when the customer dials CMC. As the call is held by CMC, the information starts to calculate the customers score to determined who will be served first(High score will be served first, the lower score will keep on waiting until RM respond). If no RM responded the call, all customer who is on hold will be transferred to the interactive voice response(IVP) unit. In the time with IVP, the customer will be asked to answer a few questions(E.x: Call Reason). The customer could choose to keep waiting or end the call in this stage. RM will be assigned to the customer. hopefully, each customer will purchase our products. This process will start again when another customer called CMC.

**Comment by leongeitmann** [comment]
This Diagram reflects how User Story 2 is addressed within the System. A detailed description how this Diagram encoporates the User story can be found here: https://github.com/leongeitmann/ISDMTut3Group1/issues/28

**Comment by Rogan-Heng** [comment]
![Uploading call in.png…]()

**Comment by Rogan-Heng** [comment]
![inbound](https://user-images.githubusercontent.com/53921261/82893024-ca398e80-9f93-11ea-948a-6d756ac1bad4.jpg)

**Comment by Rogan-Heng** [comment]
![call in](https://user-images.githubusercontent.com/53921261/82893119-e3423f80-9f93-11ea-93a7-e74a66865363.png)
