### ISSUE TITLE
Activity diagram for call out

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#15]

**Comment by JunKai-Li-1** [comment]
![Activity Diagram Outbound Call](https://user-images.githubusercontent.com/62220299/82148427-7514c300-9897-11ea-8c8b-5f19428d373b.PNG)

**Comment by JunKai-Li-1** [comment]
![Activity Diagram Outbound Call](https://user-images.githubusercontent.com/62220299/82148518-df2d6800-9897-11ea-90e5-469e259992f3.PNG)

**Comment by JunKai-Li-1** [comment]
![Activity Diagram Outbound Call](https://user-images.githubusercontent.com/62220299/82150063-2f59f980-989b-11ea-98c9-19890591798b.PNG)

**Comment by Rogan-Heng** [comment]
![outbound call](https://user-images.githubusercontent.com/53921261/82892293-927e1700-9f92-11ea-8555-208588d1675e.jpg)

**Comment by Rogan-Heng** [comment]
![call out](https://user-images.githubusercontent.com/53921261/82892695-4384b180-9f93-11ea-9d8f-8efde27688f6.PNG)
