### ISSUE TITLE
Sequence diagram for call in

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#16]

**Comment by leongeitmann** [comment]
![Sequence Diagram  Inbound PAPER VERSION](https://user-images.githubusercontent.com/62409272/82110883-a05abd80-9784-11ea-8985-bdadcef461d5.jpg)

**Comment by JunKai-Li-1** [comment]
![Sequence Diagram Inbound Call - Visio Professional 2020_5_16 15_39_35](https://user-images.githubusercontent.com/62220299/82118930-a4ef9800-97bd-11ea-8e0a-3879931ef563.png)

**Comment by leongeitmann** [comment]
Description:

The inbound call of course starts with a customer calling our insitution, where he gets connected to the CMC. Here a purchase likelihood score is assigned to the customer, based on info gathered from the call itsself (location, suburb, prefix, already purchased a product from this phone number in the past, etc.). The CMC then requests the skill scores of the RMs currently available. The skill score for each RM are being calculated automatically based on their recent performance. The best fitting RM will be assigned to each calling customer (high skill score matched with high purchase-likelihood-score). The RM and calling customer get connected and the customer will hopefully purchase one of our products.
