### ISSUE TITLE
Sequence diagram for call out

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#17]

**Comment by leongeitmann** [comment]
![Sequence Diagram  Outbound PAPER VERSION](https://user-images.githubusercontent.com/62409272/82110799-3f32ea00-9784-11ea-9621-cee470cd56ef.jpg)

**Comment by JunKai-Li-1** [comment]
![Sequence Diagram Outbound Call - Visio Professional 2020_5_16 16_04_46](https://user-images.githubusercontent.com/62220299/82118946-ade06980-97bd-11ea-94a3-b75caa3287d0.png)

**Comment by leongeitmann** [comment]
Description:

The RM is ready to call a potential customer and therefore requests a call, including customer details from the CMC. The CMC responds with all necessary information and automatically creates a list of potential customers with details for each one. After these steps the RM has signaled that he's ready to make outbound calls and has received all necessary information by the CMC to make his calls. In the next step the RM therefore calls the potential customer and tries to convince him to buy one of our holiday packages. When the call is over, the customer will have decided if he/she would like to purchase a product. The RM will note that decision and notify the CMC if the customer decided to purchase a specific product or make no purchase at all. After this the RM can call the next potential customer and the sequence begins again.
