### ISSUE TITLE
Emapthy map and POV

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#3]
Please everyone review on this one

**Comment by AungKMyat** [comment]
Help each other and review

**Comment by JunKai-Li-1** [comment]
Empathy map(Done)

**Comment by JunKai-Li-1** [comment]
POV(Done)

**Comment by leongeitmann** [comment]
<img width="717" alt="Empathy Map" src="https://user-images.githubusercontent.com/62409272/82767847-e3e0b600-9e6d-11ea-820e-624fe2e8c3f3.png">

**Comment by JunKai-Li-1** [comment]
<img width="658" alt="Screen Shot 2020-05-31 at 4 56 16 pm" src="https://user-images.githubusercontent.com/62220299/83346443-bad58f00-a35f-11ea-8eff-8824d058a324.png">
