### ISSUE TITLE
All Models / Diagrams OVERVIEW

### ISSUE THREAD

**Issue by AungKMyat** [leongeitmann/ISDMTut3Group1#9]

**Comment by JunKai-Li-1** [comment]
![Activity Diagram Call In - Visio Professional 2020_5_16 16_36_41](https://user-images.githubusercontent.com/62220299/82768879-01654e00-9e75-11ea-8685-26cf990016cc.png)
![Activity Diagram Outbound Call](https://user-images.githubusercontent.com/62220299/82768881-03c7a800-9e75-11ea-8a39-c1f456a46902.PNG)
![Class Diagram](https://user-images.githubusercontent.com/62220299/82768882-04603e80-9e75-11ea-9915-1d0a26d4d7ab.PNG)
![Sequence Diagram Inbound Call - Visio Professional 2020_5_16 15_39_35](https://user-images.githubusercontent.com/62220299/82768883-05916b80-9e75-11ea-809d-d0848a4e9882.png)
![Sequence Diagram Outbound Call - Visio Professional 2020_5_16 16_04_46](https://user-images.githubusercontent.com/62220299/82768884-05916b80-9e75-11ea-9229-8faee9156355.png)
![Use Case Call Out - Visio Professional 2020_5_16 16_58_32](https://user-images.githubusercontent.com/62220299/82768885-062a0200-9e75-11ea-8fd4-d6a6e485ee63.png)
![Usu Case Call in](https://user-images.githubusercontent.com/62220299/82768887-06c29880-9e75-11ea-902f-6e15e29d4552.PNG)

**Comment by JunKai-Li-1** [comment]
close

**Comment by JunKai-Li-1** [comment]
![Class Diagram](https://user-images.githubusercontent.com/62220299/82868657-605bbd80-9f70-11ea-9709-3367223c3f0e.PNG)

**Comment by JunKai-Li-1** [comment]
Class diagram version 2

**Comment by JunKai-Li-1** [comment]
![Usu Case Call in](https://user-images.githubusercontent.com/62220299/82973510-f3e9c880-a01a-11ea-97ec-aa9f21ad3ada.PNG)

**Comment by JunKai-Li-1** [comment]
Use Case Call in version 2
